# Emoji Sentiment

Are popular emojis generally associated with positive or negative sentiments?

The file `"emoji-sentiment.csv"` provides data on the sentiment associated with various emojis.

Researchers examined 1.6 million tweets across 13 European languages. Each tweet was labeled by annotators as positive (+1), negative (-1), or neutral (0). About 4% of these tweets included emojis.

Columns include:
- `Occurrences [5...max]`: Number of times the emoji appears in the dataset.
- `Position [0...1]`: Average position of the emoji in tweets, from start (0) to end (1).
- `Neg [0...1]`: Percentage of tweets with the emoji that are 'negative'.
- `Neu [0...1]`: Percentage of tweets with the emoji that are 'neutral'.
- `Pos [0...1]`: Percentage of tweets with the emoji that are 'positive'.

In [12]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/catalin5433/emoji-sentiment-analysis/refs/heads/main/emoji-sentiment.csv')
df

,Char,Image [twemoji],Unicode codepoint,Occurrences [5...max],Position [0...1],Neg [0...1],Neut [0...1],Pos [0...1],Sentiment bar (c.i. 95%),Unicode name,Unicode block
0,😂,😂,0x1f602,14622,0.805,0.247,0.285,0.468,NaN,FACE WITH TEARS OF JOY,Emoticons
1,❤,❤,0x2764,8050,0.747,0.044,0.166,0.790,NaN,HEAVY BLACK HEART,Dingbats
2,♥,♥,0x2665,7144,0.754,0.035,0.272,0.693,NaN,BLACK HEART SUIT,Miscellaneous Symbols
3,😍,😍,0x1f60d,6359,0.765,0.052,0.219,0.729,NaN,SMILING FACE WITH HEART-SHAPED EYES,Emoticons
4,😭,😭,0x1f62d,5526,0.803,0.436,0.220,0.343,NaN,LOUDLY CRYING FACE,Emoticons
...,...,...,...,...,...,...,...,...,...,...,...
746,♮,♮,0x266e,5,0.937,0.125,0.625,0.250,NaN,MUSIC NATURAL SIGN,Miscellaneous Symbols
747,🅾,🅾,0x1f17e,5,0.977,0.375,0.375,0.250,NaN,NEGATIVE SQUARED LATIN CAPITAL LETTER O,Enclosed Alphanumeric Supplement
748,🔄,🔄,0x1f504,5,0.971,0.125,0.750,0.125,NaN,ANTICLOCKWISE DOWNWARDS AND UPWARDS OPEN CIRCL...,Miscellaneous Symbols and Pictographs
749,☄,☄,0x2604,5,0.435,0.125,0.750,0.125,NaN,COMET,Miscellaneous Symbols
750,☨,☨,0x2628,5,0.458,0.125,0.750,0.125,NaN,CROSS OF LORRAINE,Miscellaneous Symbols

### Project Ideas:

Data Cleaning:
- Remove unnecessary columns that are not useful for your analysis.

- Rename the remaining columns using `snake_case` (all lowercase letters with underscores between words).

New Variables:
- Add a new column called `sentiment`, where sentiment = (% positive tweets) - (% negative tweets).

- Add a `positive_flag` column that is `True` if `sentiment > 0` (or above a set threshold), otherwise `False`.

Types of questions you can now answer more easily:
- What percentage of emojis in the dataset have a positive sentiment?

- What percentage of the top 20 most popular emojis are positive?

- Which emoji (with more than 500 mentions) is the most positive?

- Which emoji (with more than 500 mentions) is the most negative?

- Where in the tweets are most emojis located (i.e. at the beginning or the end)?

- Is there a difference in the placement of positive versus negative emojis within a tweet?

In [13]:
# Remove unnecessary columns
cols_to_drop = ['Image [twemoji]', 'Unicode codepoint', 'Sentiment bar (c.i. 95%)']
df = df.drop(columns=cols_to_drop)

# Rename columns to snake_case
new_column_names = {
    'Char': 'char',
    'Occurrences [5...max]': 'occurrences',
    'Position [0...1]': 'position',
    'Neg [0...1]': 'neg_prop',
    'Neut [0...1]': 'neut_prop',
    'Pos [0...1]': 'pos_prop',
    'Unicode name': 'unicode_name',
    'Unicode block': 'unicode_block'
}
df = df.rename(columns=new_column_names)

# Display the cleaned dataframe
df

,char,occurrences,position,neg_prop,neut_prop,pos_prop,unicode_name,unicode_block
0,😂,14622,0.805,0.247,0.285,0.468,FACE WITH TEARS OF JOY,Emoticons
1,❤,8050,0.747,0.044,0.166,0.790,HEAVY BLACK HEART,Dingbats
2,♥,7144,0.754,0.035,0.272,0.693,BLACK HEART SUIT,Miscellaneous Symbols
3,😍,6359,0.765,0.052,0.219,0.729,SMILING FACE WITH HEART-SHAPED EYES,Emoticons
4,😭,5526,0.803,0.436,0.220,0.343,LOUDLY CRYING FACE,Emoticons
...,...,...,...,...,...,...,...,...
746,♮,5,0.937,0.125,0.625,0.250,MUSIC NATURAL SIGN,Miscellaneous Symbols
747,🅾,5,0.977,0.375,0.375,0.250,NEGATIVE SQUARED LATIN CAPITAL LETTER O,Enclosed Alphanumeric Supplement
748,🔄,5,0.971,0.125,0.750,0.125,ANTICLOCKWISE DOWNWARDS AND UPWARDS OPEN CIRCL...,Miscellaneous Symbols and Pictographs
749,☄,5,0.435,0.125,0.750,0.125,COMET,Miscellaneous Symbols
750,☨,5,0.458,0.125,0.750,0.125,CROSS OF LORRAINE,Miscellaneous Symbols

In [14]:
# Add a new column called sentiment: (% positive) - (% negative)
df['sentiment'] = df['pos_prop'] - df['neg_prop']

# Add a positive_flag column: True if sentiment > 0, otherwise False
df['positive_flag'] = df['sentiment'] > 0

# Display the updated dataframe with new variables
df

,char,occurrences,position,neg_prop,neut_prop,pos_prop,unicode_name,unicode_block,sentiment,positive_flag
0,😂,14622,0.805,0.247,0.285,0.468,FACE WITH TEARS OF JOY,Emoticons,0.221,True
1,❤,8050,0.747,0.044,0.166,0.790,HEAVY BLACK HEART,Dingbats,0.746,True
2,♥,7144,0.754,0.035,0.272,0.693,BLACK HEART SUIT,Miscellaneous Symbols,0.658,True
3,😍,6359,0.765,0.052,0.219,0.729,SMILING FACE WITH HEART-SHAPED EYES,Emoticons,0.677,True
4,😭,5526,0.803,0.436,0.220,0.343,LOUDLY CRYING FACE,Emoticons,-0.093,False
...,...,...,...,...,...,...,...,...,...,...
746,♮,5,0.937,0.125,0.625,0.250,MUSIC NATURAL SIGN,Miscellaneous Symbols,0.125,True
747,🅾,5,0.977,0.375,0.375,0.250,NEGATIVE SQUARED LATIN CAPITAL LETTER O,Enclosed Alphanumeric Supplement,-0.125,False
748,🔄,5,0.971,0.125,0.750,0.125,ANTICLOCKWISE DOWNWARDS AND UPWARDS OPEN CIRCL...,Miscellaneous Symbols and Pictographs,0.000,False
749,☄,5,0.435,0.125,0.750,0.125,COMET,Miscellaneous Symbols,0.000,False
750,☨,5,0.458,0.125,0.750,0.125,CROSS OF LORRAINE,Miscellaneous Symbols,0.000,False

In [15]:
# Calculate the percentage of all emojis in the dataset that have a positive sentiment
positive_percentage = df['positive_flag'].mean() * 100
print(f"{positive_percentage:.2f}% of emojis in the dataset have a positive sentiment.")

82.42% of emojis in the dataset have a positive sentiment.

In [16]:
# Sort by occurrences to find the top 20 most popular emojis
top_20_emojis = df.sort_values(by='occurrences', ascending=False).head(20)
top_20_emojis

,char,occurrences,position,neg_prop,neut_prop,pos_prop,unicode_name,unicode_block,sentiment,positive_flag
0,😂,14622,0.805,0.247,0.285,0.468,FACE WITH TEARS OF JOY,Emoticons,0.221,True
1,❤,8050,0.747,0.044,0.166,0.790,HEAVY BLACK HEART,Dingbats,0.746,True
2,♥,7144,0.754,0.035,0.272,0.693,BLACK HEART SUIT,Miscellaneous Symbols,0.658,True
3,😍,6359,0.765,0.052,0.219,0.729,SMILING FACE WITH HEART-SHAPED EYES,Emoticons,0.677,True
4,😭,5526,0.803,0.436,0.220,0.343,LOUDLY CRYING FACE,Emoticons,-0.093,False
5,😘,3648,0.854,0.053,0.193,0.754,FACE THROWING A KISS,Emoticons,0.701,True
6,😊,3186,0.813,0.060,0.237,0.704,SMILING FACE WITH SMILING EYES,Emoticons,0.644,True
7,👌,2925,0.805,0.094,0.249,0.657,OK HAND SIGN,Miscellaneous Symbols and Pictographs,0.563,True
8,💕,2400,0.766,0.042,0.285,0.674,TWO HEARTS,Miscellaneous Symbols and Pictographs,0.632,True
9,👏,2336,0.787,0.104,0.271,0.624,CLAPPING HANDS SIGN,Miscellaneous Symbols and Pictographs,0.520,True
10,😁,2189,0.796,0.127,0.296,0.577,GRINNING FACE WITH SMILING EYES,Emoticons,0.450,True
11,☺,2062,0.799,0.062,0.218,0.720,WHITE SMILING FACE,Miscellaneous Symbols,0.658,True
12,♡,1975,0.764,0.052,0.227,0.721,WHITE HEART SUIT,Miscellaneous Symbols,0.669,True
13,👍,1854,0.812,0.115,0.248,0.637,THUMBS UP SIGN,Miscellaneous Symbols and Pictographs,0.522,True
14,😩,1808,0.826,0.591,0.186,0.223,WEARY FACE,Emoticons,-0.368,False
15,🙏,1539,0.794,0.081,0.421,0.498,PERSON WITH FOLDED HANDS,Emoticons,0.417,True
16,✌,1534,0.790,0.113,0.310,0.576,VICTORY HAND,Dingbats,0.463,True
17,😏,1522,0.765,0.112,0.444,0.444,SMIRKING FACE,Emoticons,0.332,True
18,😉,1521,0.845,0.100,0.337,0.563,WINKING FACE,Emoticons,0.463,True
19,🙌,1506,0.791,0.101,0.238,0.661,PERSON RAISING BOTH HANDS IN CELEBRATION,Emoticons,0.560,True

In [17]:
# Calculate the percentage of these top 20 that are positive
top_20_positive_pct = top_20_emojis['positive_flag'].mean() * 100

print(f"{top_20_positive_pct:.2f}% of the top 20 most popular emojis are positive.")
top_20_emojis[['char', 'occurrences', 'sentiment', 'positive_flag']]

90.00% of the top 20 most popular emojis are positive.

   char  occurrences  sentiment  positive_flag
0     😂        14622      0.221           True
1     ❤         8050      0.746           True
2     ♥         7144      0.658           True
3     😍         6359      0.677           True
4     😭         5526     -0.093          False
5     😘         3648      0.701           True
6     😊         3186      0.644           True
7     👌         2925      0.563           True
8     💕         2400      0.632           True
9     👏         2336      0.520           True
10    😁         2189      0.450           True
11    ☺         2062      0.658           True
12    ♡         1975      0.669           True
13    👍         1854      0.522           True
14    😩         1808     -0.368          False
15    🙏         1539      0.417           True
16    ✌         1534      0.463           True
17    😏         1522      0.332           True
18    😉         1521      0.463           True
19    🙌         1506      0.560           True

In [18]:
# Filter for emojis with more than 500 mentions and find the most positive
most_positive_500 = df[df['occurrences'] > 500].sort_values(by='sentiment', ascending=False).head(1)

print("The most positive emoji with more than 500 mentions is:")
display(most_positive_500[['char', 'unicode_name', 'occurrences', 'sentiment']])

The most positive emoji with more than 500 mentions is:

  char       unicode_name  occurrences  sentiment
1    ❤  HEAVY BLACK HEART         8050      0.746

In [19]:
# Filter for emojis with more than 500 mentions and find the most negative
most_negative_500 = df[df['occurrences'] > 500].sort_values(by='sentiment', ascending=True).head(1)

print("The most negative emoji with more than 500 mentions is:")
display(most_negative_500[['char', 'unicode_name', 'occurrences', 'sentiment']])

The most negative emoji with more than 500 mentions is:

   char   unicode_name  occurrences  sentiment
23    😒  UNAMUSED FACE         1385     -0.374

In [20]:
# Calculate the average position of emojis in tweets
avg_position = df['position'].mean()

print(f"The average position of emojis is {avg_position:.3f}.")
if avg_position > 0.5:
    print("This suggests that emojis are generally located towards the end of tweets.")
else:
    print("This suggests that emojis are generally located towards the beginning of tweets.")

The average position of emojis is 0.666.
This suggests that emojis are generally located towards the end of tweets.

In [21]:
# Group by positive_flag and calculate the mean position
position_comparison = df.groupby('positive_flag')['position'].mean()

print("Average position by sentiment category:")
print(f"Negative emojis: {position_comparison[False]:.3f}")
print(f"Positive emojis: {position_comparison[True]:.3f}")

difference = position_comparison[True] - position_comparison[False]
print(f"\nDifference (Pos - Neg): {difference:.3f}")

Average position by sentiment category:
Negative emojis: 0.681
Positive emojis: 0.662

Difference (Pos - Neg): -0.019